print("Hello, World")
print("This is an example Python file.")
print("It demonstrates basic print statements.")
print("Goodbye, World")
print("End of the example.")
print("Thank you for using this example.")
